== Group
`id` in request/reponse events are group ids

=== group.create.request
[source]
{
    "name": "my group name", // min. 3 characters; max. 64 characters;
    "password": "secret" // min. 8 characters
}

=== group.create.response
[source]
{
    "id": "7686d130-2223-4769-ab9f-5cebcf795e80"
}

=== group.created
Recipients: all joined users
[source]
{
    "id": "7686d130-2223-4769-ab9f-5cebcf795e80"
    "name": "my group nyme",
    "userId": "7686d130-2223-4769-ab9f-5cebcf795e80"
}

=== group.list.request
Request for all available groups

=== group.list.response
List of all available groups
[source]
[
    {
        "id": "7686d130-2223-4769-ab9f-5cebcf795e80",
        "name": "my group name",
        "userId": "7686d130-2223-4769-ab9f-5cebcf795e80"
    },
    ...
]

=== group.users.request
Request user ids for given group
[source]
{
    "id": "7686d130-2223-4769-ab9f-5cebcf795e80"
}

=== group.users.response
List of user ids
[source]
[
    "7686d130-2223-4769-ab9f-5cebcf795e80",
    ...
]

=== group.join.request
[source]
{
    "id": "7686d130-2223-4769-ab9f-5cebcf795e80",
    "password": "secret"
}

=== group.join.response

=== group.joined
Recipients: users in group
[source]
{
    "id": "7686d130-2223-4769-ab9f-5cebcf795e80"
    "userId": "7686d130-2223-4769-ab9f-5cebcf795e80"
}

=== group.poker.start.request
Request to start poker by group owner
[source]
{
    "id": "7686d130-2223-4769-ab9f-5cebcf795e80"
}

=== group.poker.start.response

=== group.poker.started
If poker has been started all bets in this group going to be deleted
Recipients: users in group
[source]
{
    "id": "7686d130-2223-4769-ab9f-5cebcf795e80"
}

=== group.poker.bet.request
[source]
{
    "id": "7686d130-2223-4769-ab9f-5cebcf795e80",
    "bet": 13 // allowed values: 0.5, 1, 2, 3, 5, 8, 13, 20, 30, 40, 100
}

=== group.poker.bet.response

=== group.poker.betted
Recipients: users in group
[source]
{
    "id": "7686d130-2223-4769-ab9f-5cebcf795e80",
    "userId": "7686d130-2223-4769-ab9f-5cebcf795e80"
}

=== group.poker.end.request
Request to end current poker by group onwer
[source]
{
    "id": "7686d130-2223-4769-ab9f-5cebcf795e80"
}

=== group.poker.end.response


=== group.poker.ended
Recipients: users in group
[source]
[
    {
        "id": "7686d130-2223-4769-ab9f-5cebcf795e80"
        "userId": "7686d130-2223-4769-ab9f-5cebcf795e80",
        "bet": 13
    },
    ...
]

