== Group

=== group.create.request
[source]
{
    "name": "my group name", // min. 3 characters; max. 64 characters;
    "password": "secret" // min. 8 characters
}

=== group.create.response
[source]
{
    "id": "7686d130-2223-4769-ab9f-5cebcf795e80"
}

=== group.created
Recipients: all joined users
[source]
{
    "id": "7686d130-2223-4769-ab9f-5cebcf795e80"
    "name": "my group nyme"
}

=== group.list.request

=== group.list.response
[source]
[
    {
        "id": "7686d130-2223-4769-ab9f-5cebcf795e80",
        "name": "my group name",
        "userId": "7686d130-2223-4769-ab9f-5cebcf795e80"
    },
    ...
]

=== group.invite.request
Creator of a group can invite other users
[source]
{
    "id": "7686d130-2223-4769-ab9f-5cebcf795e80",
    "userId": "7686d130-2223-4769-ab9f-5cebcf795e80"
}

=== group.invite.response

=== group.invited
Recipients: invited user
[source]
{
    "id": "7686d130-2223-4769-ab9f-5cebcf795e80"
}

=== group.invites.request
Requests all invites for groups that you have created and invites for groups you are invited to.

=== group.invites.response
[source]
[
    {
        "id": "7686d130-2223-4769-ab9f-5cebcf795e80",
        "userId": "7686d130-2223-4769-ab9f-5cebcf795e80"
    },
    ...
]

=== group.join.request
[source]
{
    "id": "7686d130-2223-4769-ab9f-5cebcf795e80",
    "password": "secret"
}

=== group.join.response

=== group.joined
Recipients: users in group
[source]
{
    "id": "7686d130-2223-4769-ab9f-5cebcf795e80"
    "userId": "7686d130-2223-4769-ab9f-5cebcf795e80"
}

=== group.join.decline.request
[source]
{
    "id": "7686d130-2223-4769-ab9f-5cebcf795e80"
    "userId": "7686d130-2223-4769-ab9f-5cebcf795e80"
}

=== group.join.decline.response

=== group.join.declined
Recipients: group owner
[source]
{
    "id": "7686d130-2223-4769-ab9f-5cebcf795e80"
}


=== group.poker.start.request
[source]
{
    "id": "7686d130-2223-4769-ab9f-5cebcf795e80"
}

=== group.poker.start.response

=== group.poker.started
Recipients: users in group
[source]
{
    "id": "7686d130-2223-4769-ab9f-5cebcf795e80"
}

=== group.poker.bet.request
[source]
{
    "id": "7686d130-2223-4769-ab9f-5cebcf795e80",
    "bet": 13 // allowed values: -1, 0.5, 1, 2, 3, 5, 8, 13, 20, 30, 40, 100
}

=== group.poker.bet.response

=== group.poker.betted
Recipients: users in group
[source]
{
    "id": "7686d130-2223-4769-ab9f-5cebcf795e80",
    "userId": "7686d130-2223-4769-ab9f-5cebcf795e80"
}

=== group.poker.end.request
[source]
{
    "id": "7686d130-2223-4769-ab9f-5cebcf795e80"
}

=== group.poker.end.response
[source]
[
    {
        "userId": "7686d130-2223-4769-ab9f-5cebcf795e80",
        "bet": 13
    },
    ...
]

=== group.poker.ended
Recipients: users in group
[source]
[
    {
        "id": "7686d130-2223-4769-ab9f-5cebcf795e80"
        "userId": "7686d130-2223-4769-ab9f-5cebcf795e80",
        "bet": 13
    },
    ...
]
