== Group
`id` in request/reponse events are group ids

=== group.create
[source]
{
    "name": "my group name", // min. 3 characters; max. 64 characters;
    "password": "secret" // min. 8 characters
}

Response
[source]
{
    "status": 200, // 401 if not joined
    "message": {
        "id": "7686d130-2223-4769-ab9f-5cebcf795e80",
        "name": "my group name",
        "userId": "7686d130-2223-4769-ab9f-5cebcf795e80",
        "poker": false
    }
}

=== group.created
Recipients: all joined users
[source]
{
    "id": "7686d130-2223-4769-ab9f-5cebcf795e80"
    "name": "my group nyme",
    "userId": "7686d130-2223-4769-ab9f-5cebcf795e80",
    "poker": false
}

=== group.list
Request for all available groups
[source]
{
}

Response
List of all available groups
[source]
{
    "status": 200, // 401 if not joined
    "message": [
        {
            "id": "7686d130-2223-4769-ab9f-5cebcf795e80",
            "name": "my group name",
            "userId": "7686d130-2223-4769-ab9f-5cebcf795e80",
            "poker": false
        },
        ...
    ]
}

=== group.users
Request user ids for given group
[source]
{
    "id": "7686d130-2223-4769-ab9f-5cebcf795e80"
}

Response:
List of user ids
[source]
{
    "status": 200, // 401 if not joined
    "message": [
        "7686d130-2223-4769-ab9f-5cebcf795e80",
        ...
    ]
}

=== group.join
[source]
{
    "id": "7686d130-2223-4769-ab9f-5cebcf795e80",
    "password": "secret"
}

Response
[source]
{
    "status": 200 // 400 if password is invalid; 401 if not joined; 404 if group does not exist; 500 if `id` or  `password` is not set
}

=== group.joined
Recipients: users in group
[source]
{
    "id": "7686d130-2223-4769-ab9f-5cebcf795e80"
    "userId": "7686d130-2223-4769-ab9f-5cebcf795e80"
}

=== group.poker.start
Request to start poker by group owner
[source]
{
    "id": "7686d130-2223-4769-ab9f-5cebcf795e80"
}

Response
[source]
{
    "status": 200 // 401 if not joined; 403 if not owner of the group; 404 if group not found; 500 if `id` not valid
}

=== group.poker.started
If poker has been started all bets in this group going to be deleted
Recipients: users in group
[source]
{
    "id": "7686d130-2223-4769-ab9f-5cebcf795e80"
}

=== group.poker.bets
Lists current bets in this group. If group is in poker state, actual bet values are hidden 
[source]
{
    "id": "7686d130-2223-4769-ab9f-5cebcf795e80"
}

Response
[source]
{
    "status": 200, // 401 if not joined; 403 if not in group; 404 if group does not exists
    "message": [
        {
            "userId": "7686d130-2223-4769-ab9f-5cebcf795e80",
            "bet": 30 // optional
        },
        ...
    ]
}


=== group.poker.bet
[source]
{
    "id": "7686d130-2223-4769-ab9f-5cebcf795e80",
    "bet": 13 // allowed values: 1, 2, 3, 5, 8, 13, 20, 30, 40, 100
}

Response
[source]
{
    "status": 200 // 401 if not joined; 404 if not in group; 500 if `bet` not valid, `id` not valid or poker has not started yet
}

=== group.poker.betted
Recipients: users in group
[source]
{
    "id": "7686d130-2223-4769-ab9f-5cebcf795e80",
    "userId": "7686d130-2223-4769-ab9f-5cebcf795e80"
}

=== group.poker.end
Request to end current poker by group onwer
[source]
{
    "id": "7686d130-2223-4769-ab9f-5cebcf795e80"
}

Response
[source]
{
    "status": 200 // 401 if not joined; 403 if not owner of the group; 404 if group not found; 500 if `id` not valid
}

=== group.poker.ended
Recipients: users in group
[source]
{
    "id": "7686d130-2223-4769-ab9f-5cebcf795e80",
    "bets": [
        {
            "userId": "7686d130-2223-4769-ab9f-5cebcf795e80",
            "bet": 13
        },
        ...
    ]
}
